services:
  # Nossa API FastAPI (A Porta de Entrada)
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # <-- Injeta as credenciais
    depends_on:
      - redis

  # Nosso Message Broker (A Fila)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Nosso Trabalhador em Segundo Plano
  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env  # <-- Injeta as credenciais
    depends_on:
      - redis